name: Setups

on:
  workflow_call:

runs:
  using: "composite"
  steps:
  - uses: actions/setup-node@v4
    with:
      node-version: 22
      cache: yarn

  - name: Restore node modules from cache
    uses: actions/cache@v4
    with:
      path: node_modules
      key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

  - name: Cache next
    uses: actions/cache@v4
    with:
      path: .next/cache
      key: nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}

  - name: Cache rotion
    uses: actions/cache@v4
    with:
      path: |
        .cache
        public/images
        public/ogimages
      key: rotion
