import type { NextPage, GetStaticProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

const API_URL = process.env.WORDPRESS_API_URL || 'https://wp.cognano.co.jp/graphql'
//const API_TOKEN = process.env.WORDPRESS_AUTH_REFRESH_TOKEN

async function fetchAPI(query, { variables } = {}) {
  const headers = {
    'Content-Type': 'application/json',
    //'Authorization': `Bearer ${API_TOKEN}`,
  }

  const res = await fetch(API_URL, {
    method: 'POST',
    headers,
    body: JSON.stringify({
      query,
      variables,
    }),
  })

  const json = await res.json()
  if (json.errors) {
    console.error(json.errors)
    throw new Error('Failed to fetch API')
  }
  return json.data
}

async function getPosts() {
  const data = await fetchAPI(
    `query AllPosts {
      posts(first: 20) {
        edges {
          node {
            title
            categories {
              edges {
                node {
                  name
                }
              }
            }
            excerpt
            slug
            author {
              node {
                name
                firstName
                lastName
              }
            }
          }
        }
      }
    }
    `,
    {
      variables: {},
    }
  )
  return data?.posts?.edges
}

export const getStaticProps: GetStaticProps<{
  posts: WPPost[]
}> = async () => {
  const posts = await getPosts()
  return {
    props: {
      posts
    }
  }
}

const Home: NextPage = ({ posts } ) => {
  return (
    <div className={styles.container}>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://www.cognano.co.jp">CogNano🦙</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        {
          posts.map((post,index) => (
            <div className={styles.grid} key={index}>
              <Link href={`/posts/${post.node.id}`}>
                <a className={styles.card}>
                  <h2>{post.node.title} &rarr;</h2>
                  <p>{post.node.excerpt.replace(/<[^>]*>?/gm, '').replace(/\r?\n/g, '').substr(0, 60)}</p>
                  <p>By {post.node.author.node.name}</p>
                </a>
              </Link>
            </div>
          ))
        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home
