name: Build

on:
  repository_dispatch:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setups
    - name: Install dependencies
      run: |
        yarn install
        yarn lint
