name: Build and Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Run builds and deploys with ${{ matrix.node-version }}
      run: |
        yarn install
        yarn lint

  deploy-to-stag:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref != 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Run next export
      run: |
        yarn install
        yarn build
    - name: Deploy to staging by FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTPHOST }}
        username: ${{ secrets.FTPUSERNAME_STAG }}
        password: ${{ secrets.FTPPASSWORD_STAG }}
        local-dir: out

  deploy-to-prod:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'yarn'
    - name: Run next export
      run: |
        yarn install
        yarn build
    - name: Deploy to production by FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTPHOST }}
        username: ${{ secrets.FTPUSERNAME_PROD }}
        password: ${{ secrets.FTPPASSWORD_PROD }}
        local-dir: out
