name: Build and Deploy

on:
  repository_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: yarn
    - name: Restore next cache
      uses: actions/cache@v3
      with:
        path: |
          .next/cache
        key: nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
    - name: Run builds and deploys with ${{ matrix.node-version }}
      run: |
        yarn install
        yarn lint

  staging:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref != 'refs/heads/main'
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTIONATE_INCREMENTAL_CACHE: true
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
    - name: Restore next cache
      uses: actions/cache@v3
      with:
        path: |
          .next/cache
        key: nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
    - name: Restore notionate cache
      uses: actions/cache@v3
      with:
        path: |
          .cache
          public/images
        key: notionate-stag
        restore-keys: notionate-stag
    - name: Install packages
      run: |
        yarn install
    - name: Run next export
      run: |
        yarn build
      env:
        NEXT_PUBLIC_LANG: en
    - name: Deploy to staging by FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTPHOST }}
        username: ${{ secrets.FTPUSERNAME_STAG_EN }}
        password: ${{ secrets.FTPPASSWORD_STAG_EN }}
        local-dir: ./out/
        exclude: |
          ogimages/*-ja-*.png
    - name: Run next export for japanese
      run: |
        yarn build
      env:
        NEXT_PUBLIC_LANG: ja
    - name: Deploy to staging by FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTPHOST }}
        username: ${{ secrets.FTPUSERNAME_STAG }}
        password: ${{ secrets.FTPPASSWORD_STAG }}
        local-dir: ./out/
        exclude: |
          ogimages/*-en-*.png

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      NOTIONATE_INCREMENTAL_CACHE: true
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: yarn
    - name: Restore next cache
      uses: actions/cache@v3
      with:
        path: |
          .next/cache
        key: nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
        restore-keys: |
          nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
    - name: Restore notionate cache
      uses: actions/cache@v3
      with:
        path: |
          .cache
          public/images
          public/ogimages
        key: notionate
        restore-keys: notionate
    - name: Install packages
      run: |
        yarn install
    - name: Run next export for english
      run: |
        yarn build
      env:
        NEXT_PUBLIC_LANG: en
    - name: Deploy to production by FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTPHOST }}
        username: ${{ secrets.FTPUSERNAME_PROD_EN }}
        password: ${{ secrets.FTPPASSWORD_PROD_EN }}
        local-dir: ./out/
        exclude: |
          ogimages/*-ja-*.png
    - name: Run next export for japanese
      run: |
        yarn build
      env:
        NEXT_PUBLIC_LANG: ja
    - name: Deploy to production by FTP
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: ${{ secrets.FTPHOST }}
        username: ${{ secrets.FTPUSERNAME_PROD }}
        password: ${{ secrets.FTPPASSWORD_PROD }}
        local-dir: ./out/
        exclude: |
          ogimages/*-en-*.png
