name: Build and Deploy

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Run builds and deploys with ${{ matrix.node-version }}
      run: |
        yarn install
        yarn lint
        yarn build

  deploy:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Deploy by SCP
      uses: appleboy/scp-action@master
      with:
        source: "out/*"
        target: ${{ secrets.STAGPATH }}
        port: ${{ secrets.PORT }}
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
