name: Release

on:
  repository_dispatch:
  workflow_dispatch:
  workflow_run:
    workflows: ["Build"]
    branches: [main]
    types: [completed]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: yarn
    - name: Cache node modules
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
    - name: Install packages
      run: yarn install

  english:
    needs: setup
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      ROTION_INCREMENTAL_CACHE: true
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: yarn
    - name: Restore node modules from cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
    - name: Cache next
      uses: actions/cache@v4
      with:
        path: .next/cache
        key: nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
    - name: Cache rotion
      uses: actions/cache@v4
      with:
        path: |
          .cache
          public/images
          public/ogimages
        key: rotion-release

    - name: Run next build for english
      run: yarn build
      env:
        NEXT_PUBLIC_LANG: en
    - name: Deploy to prod.cognanous.com by FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER_PROD_EN }}
        password: ${{ secrets.FTP_PASS_PROD_EN }}
        local-dir: ./out/
        exclude: |
          ogimages/*-ja-*.png

  japanese:
    needs: [setup, english]
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      ROTION_INCREMENTAL_CACHE: true
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: yarn
    - name: Restore node modules from cache
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
    - name: Cache next
      uses: actions/cache@v4
      with:
        path: .next/cache
        key: nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
    - name: Cache rotion
      uses: actions/cache@v4
      with:
        path: |
          .cache
          public/images
          public/ogimages
        key: rotion-release

    - name: Run next build for japanese
      run: yarn build
      env:
        NEXT_PUBLIC_LANG: ja
    - name: Deploy to prod.cognano.co.jp by FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER_PROD_JA }}
        password: ${{ secrets.FTP_PASS_PROD_JA }}
        local-dir: ./out/
        exclude: |
          ogimages/*-en-*.png
