name: Staging for English

on:
  pull_request:
  workflow_dispatch:
    inputs:
      rotionDebug:
        description: 'Rotion Debug Flag'
        required: false
        default: false
        type: boolean
  workflow_run:
    workflows:
      - 'Build'
    types: [completed]
    branches:
      - '!main'
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "staging-english"
  cancel-in-progress: false

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setups
    - name: Install packages
      run: bun install

  build:
    needs: install
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      ROTION_INCREMENTAL_CACHE: true
      ROTION_DEBUG: ${{ inputs.rotionDebug }}
      NEXT_PUBLIC_LANG: en
      BUILD_ENV: staging
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setups
    - name: Run next build for english
      run: bun run build
    - name: Save artifact
      uses: actions/upload-artifact@v4
      with:
        name: english-out-stag
        path: out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: english-out-stag
        path: out
    - name: Deploy to stag.cognanous.com by FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER_STAG_EN }}
        password: ${{ secrets.FTP_PASS_STAG_EN }}
        local-dir: ./out/
        exclude: |
          ogimages/*-ja-*.png
