name: Staging

on:
  pull_request:
  workflow_dispatch:
  workflow_run:
    workflows:
      - 'Build'
    types: [completed]
    branches:
      - '!main'
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "staging"
  cancel-in-progress: false

jobs:
  install-packages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setups
    - name: Install packages
      run: yarn install

  build-english:
    needs: install-packages
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      ROTION_INCREMENTAL_CACHE: true
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setups
    - name: Run next build for english
      run: yarn run build
      env:
        NEXT_PUBLIC_LANG: en
        BUILD_ENV: staging
    - name: Save html
      uses: actions/upload-artifact@v4
      with:
        name: english-out-stag
        path: out

  deploy-english:
    needs: build-english
    runs-on: ubuntu-latest
    steps:
    - name: Download html
      uses: actions/download-artifact@v4
      with:
        name: english-out-stag
        path: out
    - name: Deploy to stag.cognanous.com by FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER_STAG_EN }}
        password: ${{ secrets.FTP_PASS_STAG_EN }}
        local-dir: ./out/
        exclude: |
          ogimages/*-ja-*.png

  build-japanese:
    needs: build-english
    runs-on: ubuntu-latest
    env:
      NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      ROTION_INCREMENTAL_CACHE: true
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/setups
    - name: Run next build for japanese
      run: yarn run build
      env:
        NEXT_PUBLIC_LANG: ja
        BUILD_ENV: staging
    - name: Save html
      uses: actions/upload-artifact@v4
      with:
        name: japanese-out-stag
        path: out

  deploy-japanese:
    needs: build-japanese
    runs-on: ubuntu-latest
    steps:
    - name: Download html
      uses: actions/download-artifact@v4
      with:
        name: japanese-out-stag
        path: out
    - name: Deploy to stag.cognano.co.jp by FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER_STAG_JA }}
        password: ${{ secrets.FTP_PASS_STAG_JA }}
        local-dir: ./out/
        exclude: |
          ogimages/*-en-*.png
